/**
 * Typed loader over the generated enemy stat dataset (enemy-stat-data spec).
 *
 * `enemy-stats.json` is generated by `npm run extract:enemy-stats` from the
 * newserv clone (PSO Blue Burst Solo tables) — do not edit it by hand; see
 * docs/newserv-reference.md. Difficulty selects a row; no multipliers are
 * applied to these values anywhere in the engine.
 */

import rawDataset from "./enemy-stats.json";

export type Episode = "1" | "2" | "4";

/** Dataset difficulty rows. The game currently exposes normal/hard/ultimate. */
export type StatRowDifficulty = "normal" | "hard" | "vhard" | "ultimate";

export interface EnemyStatRow {
  hp: number;
  atp: number;
  dfp: number;
  ata: number;
  evp: number;
  lck: number;
  esp: number;
  exp: number;
  meseta: number;
  // Elemental resistances + flat bonuses (carried for future techniques work).
  efr: number;
  eic: number;
  eth: number;
  elt: number;
  edk: number;
  evpBonus: number;
  dfpBonus: number;
}

export interface EnemyStatEntry {
  displayName: string;
  ultimateName?: string;
  episodes: Episode[];
  perEpisode: Partial<Record<Episode, Record<StatRowDifficulty, EnemyStatRow>>>;
}

const DATASET = rawDataset as unknown as Record<string, EnemyStatEntry>;

export function getEnemyStatEntry(type: string): EnemyStatEntry {
  const entry = DATASET[type];
  if (!entry) throw new Error(`unknown enemy type in stat dataset: ${type}`);
  return entry;
}

export function getEnemyStats(
  type: string,
  episode: Episode,
  difficulty: StatRowDifficulty,
): EnemyStatRow {
  const entry = getEnemyStatEntry(type);
  const rows = entry.perEpisode[episode];
  if (!rows) throw new Error(`enemy ${type} has no episode ${episode} stats`);
  return rows[difficulty];
}

/** Display name, honoring PSO's Ultimate-mode renames (Booma → Bartle, ...). */
export function enemyDisplayName(type: string, difficulty: StatRowDifficulty): string {
  const entry = getEnemyStatEntry(type);
  return difficulty === "ultimate" && entry.ultimateName ? entry.ultimateName : entry.displayName;
}
