/**
 * Typed accessor over the authentic attack-animation frame data
 * (attack-frame-data spec; generated by scripts/extract-frame-data.mjs from the
 * pinned pioneer2.net wikitext — see frame-data.json's `source`).
 *
 * Frame counts (30 fps) are converted to integer game-milliseconds exactly once
 * here at module init; the simulation only ever sees ms. Each cell holds two
 * measured anchors — 0% ("base") and +40% ("v101") animation speed — and the
 * effective duration at a unit boost p is the integer fixed-point interpolation
 *   ms(p) = ms0 − round((ms0 − ms40) × p / 40)
 * which reproduces both anchors exactly (design D1).
 *
 * Rigs are sparse overrides over the male animations (the wiki's convention):
 * a rig/kind with no entry falls back to male. Special attacks use Heavy timing
 * (the wiki's rule; exotic per-weapon animations are out of scope).
 */

import type { AttackType } from "../combat";
import type { Rig } from "../classes";
import { WEAPON_KIND_NAMES, type WeaponKindName } from "../items";
import dataset from "./frame-data.json";

export type { Rig };

/** Per-combo-step durations (game ms) for one rig × kind × tier at one anchor. */
interface StepMs {
  full1: number;
  combo1: number;
  full2: number;
  combo2: number;
  full3: number;
}

interface TierMs {
  v101: StepMs;
  base: StepMs;
}

type Tier = "normal" | "heavy";

const MAX_BOOST = 40; // the +40% anchor; boosts are clamped to [0, 40]

function framesToMs(frames: Record<string, number>): StepMs {
  const ms = {} as Record<string, number>;
  for (const [pos, f] of Object.entries(frames)) ms[pos] = Math.round((f * 1000) / 30);
  return ms as unknown as StepMs;
}

// Convert every cell frames→ms once at init (attack-frame-data spec).
const TABLE: Partial<Record<Rig, Partial<Record<WeaponKindName, Record<Tier, TierMs>>>>> = {};
for (const [rig, kinds] of Object.entries(dataset.rigs)) {
  const rigTable: Partial<Record<WeaponKindName, Record<Tier, TierMs>>> = {};
  for (const [kind, tiers] of Object.entries(kinds)) {
    rigTable[kind as WeaponKindName] = {
      normal: { v101: framesToMs(tiers.normal.v101), base: framesToMs(tiers.normal.base) },
      heavy: { v101: framesToMs(tiers.heavy.v101), base: framesToMs(tiers.heavy.base) },
    };
  }
  TABLE[rig as Rig] = rigTable;
}

for (const kind of WEAPON_KIND_NAMES) {
  if (!TABLE.male?.[kind]) {
    throw new Error(`frame-data.json is missing male/${kind} — regenerate with extract:frame-data`);
  }
}

/** Integer fixed-point lerp between the anchors; exact at p=0 and p=40 (design D1). */
function lerpMs(ms0: number, ms40: number, boost: number): number {
  const p = Math.min(Math.max(boost, 0), MAX_BOOST);
  return ms0 - Math.round(((ms0 - ms40) * p) / MAX_BOOST);
}

/**
 * Duration (game ms) billed by a just-performed combo step. `step` is 0-based
 * (0..2). A step that chains into another attack bills its Combo duration; the
 * step that ends the burst (`isFinal`) bills its Full duration, which includes
 * the animation's recovery tail. Step 2 has no Combo flavor — the combo cannot
 * continue past it, so it always bills Full.
 */
export function attackStepMs(
  rig: Rig,
  weaponKind: number,
  attackType: AttackType,
  step: number,
  isFinal: boolean,
  speedBoost: number,
): number {
  const kindName = WEAPON_KIND_NAMES[weaponKind];
  if (kindName === undefined) throw new Error(`unknown WeaponKind ${weaponKind}`);
  // Sparse rigs fall back to the male animations (wiki convention); the male
  // table is asserted complete at init, so the lookup is total.
  const tiers = TABLE[rig]?.[kindName] ?? TABLE.male![kindName]!;
  const tier = tiers[attackType === "normal" ? "normal" : "heavy"]; // special = heavy timing
  let pos: keyof StepMs;
  if (step <= 0) pos = isFinal ? "full1" : "combo1";
  else if (step === 1) pos = isFinal ? "full2" : "combo2";
  else pos = "full3";
  return lerpMs(tier.base[pos], tier.v101[pos], speedBoost);
}
