/**
 * Typed loader over the generated item dataset (item-parameter-data spec).
 *
 * `item-table.json` is generated by `npm run extract:item-table` from the
 * newserv clone (BB item parameter table + name table) — do not edit it by
 * hand; see docs/newserv-reference.md. This module is the only reader of the
 * JSON. Mag and tool entries are extracted for future work but deliberately
 * not exposed here.
 *
 * Codes are 6-hex-digit PSO item codes (TTGGII). Entries with no display name
 * (the bare-hands weapon, unnamed tech-disk slots) are excluded from the
 * `all*()` iterators but still resolvable by code.
 */

import { archetypeForWeaponKind, type Rarity, type EquipRequirements } from "../items";
import type { GearTemplate } from "../loot";
import type { Stats } from "../stats";
import rawDataset from "./item-table.json";

export interface WeaponDef {
  code: string;
  name: string | null;
  group: number;
  weaponKind: number;
  atpMin: number;
  atpMax: number;
  ata: number;
  mst: number;
  maxGrind: number;
  atpRequired: number;
  ataRequired: number;
  mstRequired: number;
  usableBy: number;
  special: number;
  stars: number;
  /** null = unsellable (S-ranks etc.). */
  saleDivisor: number | null;
}

export interface ArmorDef {
  code: string;
  name: string | null;
  dfp: number;
  evp: number;
  dfpRange: number;
  evpRange: number;
  efr: number;
  eic: number;
  eth: number;
  elt: number;
  edk: number;
  requiredLevel: number;
  usableBy: number;
  stars: number;
}

export type FrameDef = ArmorDef;
export type BarrierDef = ArmorDef;

export interface UnitDef {
  code: string;
  name: string | null;
  stat: number;
  statAmount: number;
  modifierAmount: number;
  stars: number;
}

interface Dataset {
  armorSaleDivisor: number;
  shieldSaleDivisor: number;
  unitSaleDivisor: number;
  weapons: Record<string, Omit<WeaponDef, "code">>;
  frames: Record<string, Omit<ArmorDef, "code">>;
  barriers: Record<string, Omit<ArmorDef, "code">>;
  units: Record<string, Omit<UnitDef, "code">>;
  // mags/tools present in the JSON but intentionally untyped/unexposed.
}

const dataset = rawDataset as unknown as Dataset;

/** Star value → the engine's three-tier rarity (raw stars stay on the def). */
export function rarityForStars(stars: number): Rarity {
  if (stars >= 9) return "rare";
  if (stars >= 4) return "uncommon";
  return "common";
}

function withCode<T>(code: string, def: T | undefined): (T & { code: string }) | null {
  return def === undefined ? null : { ...def, code };
}

export function weaponDef(code: string): WeaponDef | null {
  return withCode(code, dataset.weapons[code]);
}
export function frameDef(code: string): FrameDef | null {
  return withCode(code, dataset.frames[code]);
}
export function barrierDef(code: string): BarrierDef | null {
  return withCode(code, dataset.barriers[code]);
}
export function unitDef(code: string): UnitDef | null {
  return withCode(code, dataset.units[code]);
}

function named<T extends { name: string | null }>(defs: Record<string, Omit<T, "code">>): T[] {
  return Object.entries(defs)
    .filter(([, d]) => (d as { name: string | null }).name !== null)
    .map(([code, d]) => ({ ...d, code }) as unknown as T);
}

export function allWeapons(): WeaponDef[] {
  return named<WeaponDef>(dataset.weapons);
}
export function allFrames(): FrameDef[] {
  return named<FrameDef>(dataset.frames);
}
export function allBarriers(): BarrierDef[] {
  return named<BarrierDef>(dataset.barriers);
}
export function allUnits(): UnitDef[] {
  return named<UnitDef>(dataset.units);
}

/**
 * Unit `stat` index → engine stat key (derived from the unit names in the
 * source table: 0 POW, 1 MIND, 2 ARM, 3 LEGS, 4 HP, 5 TP, 6 BODY, 7 LUCK).
 * Indexes the engine has no stat for (TP, resists, regen, cures, …) yield no
 * bonus.
 */
const UNIT_STAT_KEY: Record<number, keyof Stats> = {
  0: "atp",
  1: "mst",
  2: "ata",
  3: "evp",
  4: "hp",
  6: "dfp",
  7: "lck",
};

export function unitBonus(def: UnitDef): Partial<Stats> {
  const key = UNIT_STAT_KEY[def.stat];
  return key === undefined ? {} : { [key]: def.statAmount };
}

/** Source stat index for attack-speed units (…/Battle series). */
const STAT_ATTACK_SPEED = 19;
/**
 * V101's speed effect is hardcoded in the original client rather than data-
 * driven — its table entry uses an unrelated stat (8/15/modifier 1), yet the
 * community-measured frame data labels the +40% tables "V101" outright. It is
 * normalized to a 40% boost here (item-parameter-data spec).
 */
const V101_CODE = "010349";

/** Attack-speed boost percent granted by a unit (0 for non-speed units). */
export function unitAttackSpeedBoost(def: UnitDef): number {
  if (def.code === V101_CODE) return 40;
  return def.stat === STAT_ATTACK_SPEED ? def.statAmount : 0;
}

/**
 * PLACEHOLDER pricing until the shop/drop-table port brings the authentic
 * client formulas: buy ≈ potency²/saleDivisor (the documented PMT shape),
 * sell = buy/8 (PSO's sell ratio). Non-contractual — nothing extracted
 * circulates yet, and retuning this touches no generated data.
 */
function sellValueFor(potency: number, saleDivisor: number | null): number {
  if (saleDivisor === null || saleDivisor <= 0) return 0;
  return Math.max(1, Math.floor((potency * potency) / saleDivisor / 8));
}

function requirementsFor(def: {
  atpRequired?: number;
  ataRequired?: number;
  mstRequired?: number;
  requiredLevel?: number;
  usableBy: number;
}): EquipRequirements | undefined {
  const req: EquipRequirements = {};
  if (def.atpRequired) req.atp = def.atpRequired;
  if (def.ataRequired) req.ata = def.ataRequired;
  if (def.mstRequired) req.mst = def.mstRequired;
  if (def.requiredLevel) req.level = def.requiredLevel;
  if (def.usableBy !== 0xff) req.usableBy = def.usableBy;
  return Object.keys(req).length > 0 ? req : undefined;
}

/**
 * Bridge an item code to the engine's template model (the supported entry
 * point for future drop-table/shop work; nothing calls it from live content
 * yet). Weapons keep their authentic animation category (`weaponKind`, which
 * drives frame-data timing) plus its coarse display archetype. Frames get
 * PSO's maximum 4 unit slots
 * (per-drop slot rolls are deferred with the drop-table port), and armor
 * DFP/EVP use the base values (per-drop range rolls likewise deferred).
 */
export function templateFromCode(code: string): GearTemplate {
  const w = weaponDef(code);
  if (w) {
    return {
      kind: "weapon",
      defId: code,
      name: w.name ?? code,
      weaponType: archetypeForWeaponKind(w.weaponKind),
      minAtp: w.atpMin,
      spread: w.atpMax - w.atpMin,
      attribute: 0,
      ata: w.ata,
      grind: 0,
      maxGrind: w.maxGrind,
      group: w.group,
      weaponKind: w.weaponKind,
      rarity: rarityForStars(w.stars),
      sellValue: sellValueFor(w.atpMax, w.saleDivisor),
      requirements: requirementsFor(w),
    };
  }
  const f = frameDef(code);
  if (f) {
    return {
      kind: "frame",
      defId: code,
      name: f.name ?? code,
      dfp: f.dfp,
      evp: f.evp,
      unitSlots: 4,
      rarity: rarityForStars(f.stars),
      sellValue: sellValueFor(f.dfp + f.evp, dataset.armorSaleDivisor),
      requirements: requirementsFor(f),
    };
  }
  const b = barrierDef(code);
  if (b) {
    return {
      kind: "barrier",
      defId: code,
      name: b.name ?? code,
      dfp: b.dfp,
      evp: b.evp,
      rarity: rarityForStars(b.stars),
      sellValue: sellValueFor(b.dfp + b.evp, dataset.shieldSaleDivisor),
      requirements: requirementsFor(b),
    };
  }
  const u = unitDef(code);
  if (u) {
    const speedBoost = unitAttackSpeedBoost(u);
    return {
      kind: "unit",
      defId: code,
      name: u.name ?? code,
      bonus: unitBonus(u),
      ...(speedBoost > 0 ? { attackSpeedBoost: speedBoost } : {}),
      rarity: rarityForStars(u.stars),
      sellValue: sellValueFor(u.statAmount * 10, dataset.unitSaleDivisor),
    };
  }
  throw new Error(`unknown item code ${code} (not a weapon/frame/barrier/unit)`);
}
