/**
 * Typed loader over the generated free-play map spawn dataset.
 *
 * `map-spawns.json` is generated by `npm run extract:map-spawns` from the
 * newserv clone (BB free-play map files + set data tables) — do not edit it
 * by hand; see docs/newserv-reference.md.
 *
 * Every floor carries the authentic map variations ("configurations") vanilla
 * free play can roll: pick one (e.g. with the run's seeded RNG) and its waves
 * are the exact vanilla spawn layout. Enemy type strings are EnemyType names —
 * the keys of enemy-stats.json. Set entries that force a rare variant are
 * already counted under the rare type; ordinary spawns can additionally be
 * upgraded via `rareTypeFor` (BB rolls each spawn server-side, vanilla
 * default rate 1/512).
 */

import rawDataset from "./map-spawns.json";
import type { Episode } from "./enemy-stats";

export interface SpawnWave {
  room: number;
  wave: number;
  /** Enemy type -> spawn count. */
  enemies: Record<string, number>;
}

export interface SpawnVariation {
  /** Source enemy-set file in the newserv clone (for provenance/debugging). */
  file: string;
  waves: SpawnWave[];
}

export interface FloorSpawns {
  floor: number;
  /** PSO area number (drop tables and rare-variant rules key off this). */
  area: number;
  name: string;
  boss?: boolean;
  online: SpawnVariation[];
  offline: SpawnVariation[];
}

export type SpawnMode = "online" | "offline";

const DATASET = rawDataset as unknown as Record<Episode, FloorSpawns[]>;

export function listFloors(episode: Episode): FloorSpawns[] {
  return DATASET[episode];
}

export function getFloorSpawns(episode: Episode, floor: number): FloorSpawns {
  const entry = DATASET[episode].find((f) => f.floor === floor);
  if (!entry) throw new Error(`no spawn data for episode ${episode} floor ${floor}`);
  return entry;
}

export function getFloorSpawnsByName(episode: Episode, name: string): FloorSpawns {
  const entry = DATASET[episode].find((f) => f.name === name);
  if (!entry) throw new Error(`no spawn data for episode ${episode} area "${name}"`);
  return entry;
}

/**
 * Rare variant an enemy type can be upgraded to on a given area, or null if
 * it has none (EnemyTypeDefinition::rare_type in newserv's src/EnemyType.cc).
 * Ep2 Rag Rappy's rare form is seasonal-event-dependent; LOVE_RAPPY is the
 * no-event value.
 */
export function rareTypeFor(type: string, area: number): string | null {
  switch (type) {
    case "HILDEBEAR":
      return "HILDEBLUE";
    case "RAG_RAPPY":
      return area < 0x12 ? "AL_RAPPY" : "LOVE_RAPPY";
    case "POISON_LILY":
      return "NAR_LILY";
    case "POFUILLY_SLIME":
      return "POUILLY_SLIME";
    case "SAND_RAPPY_CRATER":
      return "DEL_RAPPY_CRATER";
    case "SAND_RAPPY_DESERT":
      return "DEL_RAPPY_DESERT";
    case "MERISSA_A":
      return "MERISSA_AA";
    case "ZU_CRATER":
      return "PAZUZU_CRATER";
    case "ZU_DESERT":
      return "PAZUZU_DESERT";
    case "DORPHON":
      return "DORPHON_ECLAIR";
    case "SAINT_MILION":
    case "SHAMBERTIN":
      return "KONDRIEU";
    default:
      return null;
  }
}
