/**
 * Typed loader over the generated room-geometry dataset (room-geometry-data
 * spec).
 *
 * `room-geometry.json` is generated by `npm run extract:room-geometry` from
 * the newserv clone's room layout index + offline set data table — do not
 * edit it by hand; see docs/newserv-reference.md.
 *
 * Covers Ep1 non-boss floors only. Each floor maps its offline spawn
 * variation files to a layout key (`"<area_hex>-<layout_hex>"`, the
 * room-layout-index key of the pre-authored map the variation plays on) and
 * carries each layout's authentic room positions (top-down x/z). The engine
 * never simulates with geometry — it exists so stage generation can stamp
 * provenance and the minimap can place rooms.
 */

import rawDataset from "./room-geometry.json";
import { getFloorLayouts } from "./room-layouts";
import type { Episode } from "./enemy-stats";

// Kept as a public re-export for callers that previously obtained provenance
// through this full-geometry module. Simulation imports room-layouts directly.
export { layoutKeyForFile } from "./room-layouts";

export interface GeometryRoom {
  /** Authentic room id (matches SpawnWave.room). */
  room: number;
  x: number;
  z: number;
}

export interface FloorGeometry {
  floor: number;
  /** PSO area number (the layout-key prefix). */
  area: number;
  name: string;
  /** Offline spawn-variation file -> layout key of the map it plays on. */
  fileToLayout: Record<string, string>;
  /** Layout key -> every room of that pre-authored map. */
  layouts: Record<string, GeometryRoom[]>;
}

type CoordinateFloor = Omit<FloorGeometry, "fileToLayout">;
const DATASET = rawDataset as unknown as Partial<Record<Episode, CoordinateFloor[]>>;

export function getFloorGeometry(episode: Episode, floor: number): FloorGeometry | null {
  const coordinates = DATASET[episode]?.find((f) => f.floor === floor);
  const provenance = getFloorLayouts(episode, floor);
  return coordinates && provenance ? { ...coordinates, fileToLayout: provenance.fileToLayout } : null;
}

/** Room positions of a rolled layout, or null when no geometry exists. */
export function layoutRooms(episode: Episode, floor: number, layoutKey: string): GeometryRoom[] | null {
  return getFloorGeometry(episode, floor)?.layouts[layoutKey] ?? null;
}
