/**
 * Typed loader over the generated room-geometry dataset (room-geometry-data
 * spec).
 *
 * `room-geometry.json` is generated by `npm run extract:room-geometry` from
 * the newserv clone's room layout index + offline set data table — do not
 * edit it by hand; see docs/newserv-reference.md.
 *
 * Covers Ep1 non-boss floors only. Each floor maps its offline spawn
 * variation files to a layout key (`"<area_hex>-<layout_hex>"`, the
 * room-layout-index key of the pre-authored map the variation plays on) and
 * carries each layout's authentic room positions (top-down x/z). The engine
 * never simulates with geometry — it exists so stage generation can stamp
 * provenance and the minimap can place rooms.
 */

import rawDataset from "./room-geometry.json";
import type { Episode } from "./enemy-stats";

export interface GeometryRoom {
  /** Authentic room id (matches SpawnWave.room). */
  room: number;
  x: number;
  z: number;
}

export interface FloorGeometry {
  floor: number;
  /** PSO area number (the layout-key prefix). */
  area: number;
  name: string;
  /** Offline spawn-variation file -> layout key of the map it plays on. */
  fileToLayout: Record<string, string>;
  /** Layout key -> every room of that pre-authored map. */
  layouts: Record<string, GeometryRoom[]>;
}

const DATASET = rawDataset as unknown as Partial<Record<Episode, FloorGeometry[]>>;

export function getFloorGeometry(episode: Episode, floor: number): FloorGeometry | null {
  return DATASET[episode]?.find((f) => f.floor === floor) ?? null;
}

/** Layout key a spawn variation file plays on, or null (boss floors, Ep2/4). */
export function layoutKeyForFile(episode: Episode, floor: number, file: string): string | null {
  return getFloorGeometry(episode, floor)?.fileToLayout[file] ?? null;
}

/** Room positions of a rolled layout, or null when no geometry exists. */
export function layoutRooms(episode: Episode, floor: number, layoutKey: string): GeometryRoom[] | null {
  return getFloorGeometry(episode, floor)?.layouts[layoutKey] ?? null;
}
