/**
 * Typed access to the extracted BB shop random-set dataset (shop-table-data
 * spec). Generated by `npm run extract:shop-tables` from the newserv clone;
 * see the extractor for the provenance of the code-baked constants.
 */

import dataset from "./shop-tables.json";
import type { SectionId } from "../classes";
import type { DropDifficulty } from "../drop-gen";

/** [value, weight] pair as used by newserv's ProbabilityTable expansion. */
export type WeightedEntry = [number, number];
/** [min, max] inclusive index/value range. */
export type Range = [number, number];

export interface TechDiskLevelMode {
  PlayerLevelDivisor?: number;
  MinLevel?: number;
  MaxLevel?: number;
}

export interface WeaponShopTables {
  /** [tier][sectionIdIndex] list of [weaponTypeCode, weight]. */
  typeWeightTables: WeightedEntry[][][];
  bonusTypeTable1: WeightedEntry[][];
  bonusTypeTable2: WeightedEntry[][];
  /** [tier] index ranges into bonusValues. */
  bonusRangeTable1: Range[];
  bonusRangeTable2: Range[];
  /** [tier] list of [mode 0|1|2, weight]. */
  specialModeTable: WeightedEntry[][];
  /** [tier] grind [min, max]. */
  defaultGrindRangeTable: Range[];
  favoredGrindRangeTable: Range[];
}

interface ShopTablesDataset {
  sectionIds: SectionId[];
  armor: {
    armorTable: WeightedEntry[][];
    shieldTable: WeightedEntry[][];
    unitTable: WeightedEntry[][];
  };
  tool: {
    /** itemDefs index → tool item code (null = "nothing" sentinel 0x0F). */
    itemDefs: (string | null)[];
    techNumMap: { tech: number; name: string }[];
    commonRecoveryTable: number[][];
    rareRecoveryTable: WeightedEntry[][];
    techDiskTable: WeightedEntry[][];
    techDiskLevelTable: TechDiskLevelMode[][];
  };
  weapon: Record<DropDifficulty, WeaponShopTables>;
  /** weapon type code → item code (null for the per-section 0x39/0x3A slots). */
  weaponTypeDefs: (string | null)[];
  weaponTypeDefs39: string[];
  weaponTypeDefs3A: string[];
  bonusValues: number[];
  /** sectionIdIndex → favored weapon type (data1[1]) or null. */
  favoredWeaponType: (number | null)[];
}

export const SHOP_TABLES = dataset as unknown as ShopTablesDataset;

/** "No item" sentinel in tool-shop tables (index 0x0F). */
export const TOOL_SHOP_NOTHING = 0x0f;

export function sectionIdIndex(sectionId: SectionId): number {
  const index = SHOP_TABLES.sectionIds.indexOf(sectionId);
  if (index < 0) throw new Error(`unknown section ID: ${sectionId}`);
  return index;
}

export function weaponShopTables(difficulty: DropDifficulty): WeaponShopTables {
  const tables = SHOP_TABLES.weapon[difficulty];
  if (!tables) throw new Error(`missing weapon shop tables for ${difficulty}`);
  return tables;
}

/**
 * Resolve a weapon-type-weight-table code to an item code. Codes 0x39/0x3A are
 * section-ID-dependent rares (ShopRandomSets.cc type_defs_39/type_defs_3A).
 */
export function weaponCodeForTypeCode(typeCode: number, sectionIndex: number): string {
  if (typeCode === 0x39) return SHOP_TABLES.weaponTypeDefs39[sectionIndex];
  if (typeCode === 0x3a) return SHOP_TABLES.weaponTypeDefs3A[sectionIndex];
  const code = SHOP_TABLES.weaponTypeDefs[typeCode];
  if (!code) throw new Error(`unmapped weapon type code 0x${typeCode.toString(16)}`);
  return code;
}

/** Tool-shop table entry → tool item code, or null for the "nothing" sentinel. */
export function toolCodeForEntry(entry: number): string | null {
  const code = SHOP_TABLES.tool.itemDefs[entry];
  if (code === undefined) throw new Error(`unmapped tool shop entry ${entry}`);
  return code;
}
